image: Visual Studio 2019

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false
  
dotnet_csproj:
  patch: true
#  file: 'Build\CodeJam.Default.props'
  version: '$(version)'
  package_version: '$(version)'


before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: EDILibrary.sln

deploy:
  provider: NuGet
  skip_symbols: true
  artifact: /.*\.nupkg/
  
artifacts:
  - path: '**\*.nupkg' # find all NuGet packages recursively
    name: Nuget packages