image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: EDILibrary.sln

deploy:
  provider: NuGet
  api_key:
    secure: cZfZAsgKc3vpblzCf7AVM//wiwGUOubDjeZeCprEss6lAbxtNH/G8R8rfpaL7ATi
  skip_symbols: true
  artifact: /.*\.nupkg/
  
artifacts:
  - path: '**\*.nupkg' # find all NuGet packages recursively
    name: Nuget packages