<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <OutputTypeEx>library</OutputTypeEx>
    <Description>EDI Library for german energy market (.net 5 version)</Description>
    <PackageId>EDILibrary.Core</PackageId>
    <Authors>EDILibrary.Core</Authors>
    <Company>EDILibrary.Core</Company>
    <Product>EDILibrary.Core</Product>
    <Version>1.5.3</Version>
    <AssemblyName>EDILibrary.Core</AssemblyName>
    <RootNamespace>EDILibrary</RootNamespace>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None
      Include="..\EDIFileLoader\EDIFileLoader.licenseheader"
      Link="EDIFileLoader.licenseheader"
    />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="MurmurHash.NETStandard" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SourceLink.Copy.PdbFiles" PrivateAssets="All" />
  </ItemGroup>
</Project>
