<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EDIFileLoader.Core</AssemblyName>
    <RootNamespace>EDIFileLoader.Core</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Joscha Metze</Authors>
    <Company>Hochfrequenz Unternehmensberatung GmbH</Company>
    <Version>1.4.4</Version>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\EDIFileLoader\AzureStorageLoader.cs" Link="AzureStorageLoader.cs" />
    <Compile Include="..\EDIFileLoader\StorageNetLoader.cs" Link="StorageNetLoader.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EDILibrary\EDILibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="Storage.Net" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="SourceLink.Copy.PdbFiles" PrivateAssets="All" />
  </ItemGroup>
</Project>
