<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>EDIFileLoader for AzureStorageAccounts</Description>
    <Copyright>Hochfrequenz Unternehmensberatung 2017</Copyright>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <Version>1.0.1</Version>
    <TargetFrameworks>net9.0;netstandard2.1</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Storage.Net" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EDILibraryBase\EDILibrary.Standard.csproj" />
  </ItemGroup>
</Project>
