name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10
      - name: Build/Check for compile errors (dotnet build)
        run: dotnet build --configuration Release
