name: csharpier

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.100
      - name: Restore .NET tools
        run: dotnet tool restore
      - name: Run CSharpier
        run: dotnet csharpier check EDILibrary.sln
