name: dotnet-format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.201
      - name: Install dotnet-format
        run: |
          dotnet tool install -g dotnet-format
      - name: Run dotnet-format
        run: dotnet-format EDILibrary.sln --check
