name: Unittests and Coverage

on: [push, pull_request]

jobs:
  unittest:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          dotnet-version: ["9.0.100"]
      steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ matrix.dotnet-version }}
        - name: Run Tests
          run: dotnet test --configuration Release
  coverage:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.100
      - name: Install dependencies
        run: dotnet restore
      - name: Install coverlet.msbuild in EDILibraryTests
        working-directory: ./EDILibraryTests
        run: dotnet add package coverlet.msbuild
      - name: Measure Test Coverage
        run: dotnet test /p:Threshold=7 /p:Include=\"[*]EDILibrary.*\" /p:ThresholdType=line /p:CollectCoverage=true /p:SkipAutoProps=true /p:CoverletOutputFormat=lcov --configuration Release
